# environment.yaml
name: MugGWAS
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - gffutils=0.13
  - pandas=2.1.4
  - biopython=1.81
  - argh=0.26.2
  - dendropy
  - multiprocessing
  - concurrent.futures
  - time
